In [36]:
import numpy as np
def lcs2(a, b):
    m = len(a) + 1
    n = len(b) + 1
    
    dp = np.zeros((m, n))
    
    for i in range(m):
        for j in range(n):
            if i == 0:
                dp[i][j] = j
            elif j == 0:
                dp[i][j] = i
            elif a[i-1] == b[j-1]:
                dp[i][j] = dp[i-1][j-1]
            else:
                dp[i][j] = min( 1 + dp[i][j-1],  # insert
                                1 + dp[i-1][j],) # remove
                
    common_sequence = []
    while (len(a) > 0) and (len(b) > 0):
        if a[-1] == b[-1]:
            common_sequence.append(a[-1])
            a.pop()
            b.pop()
            i -= 1
            j -= 1
        elif dp[i][j]-1 == dp[i-1][j]: # remove
            a.pop()
            i -= 1
        elif dp[i][j]-1 == dp[i][j-1]: # insert
            b.pop()
            j -= 1
    return dp, common_sequence

In [37]:
lcs2([2, 7, 8, 3], [5, 2, 8, 7])

(array([[0., 1., 2., 3., 4.],
        [1., 2., 1., 2., 3.],
        [2., 3., 2., 3., 2.],
        [3., 4., 3., 2., 3.],
        [4., 5., 4., 3., 4.]]),
 [7, 2])

In [39]:
lcs2([7], [1, 2, 3, 4])

(array([[0., 1., 2., 3., 4.],
        [1., 2., 3., 4., 5.]]),
 [])

In [41]:
lcs2([2, 7, 5], [2, 5])

(array([[0., 1., 2.],
        [1., 0., 1.],
        [2., 1., 2.],
        [3., 2., 1.]]),
 [5, 2])