import numpy as np
def distribute_to_3(lst, mean):
    if int(mean) != mean:
        return -1
    else:
        mean = int(mean)
    
    m = len(lst) + 1
    n = mean + 1
    
    dp = np.zeros((2, n))
    
    for i in range(1, m):
        r = i%2
        for j in range(1, n):
            num = lst[i-1]
            if r == 0:
                if num > j:
                    dp[r][j] = dp[r+1][j]
                else:
                    dp[r][j] = max( num + dp[r+1][j-num],
                                    dp[r+1][j])
            else:
                if num > j:
                    dp[r][j] = dp[r-1][j]
                else:
                    dp[r][j] = max( num + dp[r-1][j-num],
                                    dp[r-1][j])
                    
                    
                    
    if r == 0:
        dp[0], dp[1] = dp[1], dp[0]
    return dp

In [34]:
def precheck(lst):
    mean = sum(lst)/3
    if int(mean) != mean or len(lst) < 3:
        return False
    else:
        return True

In [172]:
import numpy as np
def distribute_to_3pro(lst, mean):
    m = len(lst) + 1
    n = mean + 1
    
    dp = np.zeros((m, n))
    lst = sorted(lst)
    for i in range(1, m):
        for j in range(1, n):
            num = lst[i-1]
            if num > j:
                dp[i][j] = dp[i-1][j]
            else:
                dp[i][j] = max( num + dp[i-1][j-num],
                                      dp[i-1][j])
                
            
    lst_copy = lst[:]
    i = m-1
    j = mean
    while j > 0 and i > 1:
        num = lst[i-1]
        if (num + dp[i-1][j-num]) >= dp[i-1][j]:
            if num > j:
                i -= 1
            else:
                lst_copy.remove(num)
                i -= 1
                j -= num
        else:
            i -= 1
    return dp, lst_copy

In [176]:
def main():
    lst = list(map(int, input().strip().split()))
    #lst = [17, 59, 34, 57, 17, 23, 67, 1, 18, 2, 59]
    mean = sum(lst)/3
    
    if precheck(lst):
        mean = int(mean)
        dp, lst = distribute_to_3pro(lst, mean)
    else:
        return 0
    
    dp, lst = distribute_to_3pro(lst, mean)
    if dp[-1][-1] == mean:
        return 1
    else:
        return 0

In [177]:
main()

 17 59 34 57 17 23 67 1 18 2 59


1

In [175]:
lst = [17, 59, 34, 57, 17, 23, 67, 1, 18, 2, 59]
mean = 118
distribute_to_3pro(lst, mean)

(array([[  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   1.,   1., ...,   1.,   1.,   1.],
        [  0.,   1.,   2., ...,   3.,   3.,   3.],
        ...,
        [  0.,   1.,   2., ..., 116., 117., 118.],
        [  0.,   1.,   2., ..., 116., 117., 118.],
        [  0.,   1.,   2., ..., 116., 117., 118.]]),
 [1, 2, 17, 18, 23, 57, 59, 59])

In [160]:
lst = [59, 57, 17, 23, 1, 18, 2, 59]
mean = 118
distribute_to_3pro(lst, mean)

(array([[  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   1.,   1., ...,   1.,   1.,   1.],
        [  0.,   1.,   2., ...,   3.,   3.,   3.],
        ...,
        [  0.,   1.,   2., ..., 116., 117., 118.],
        [  0.,   1.,   2., ..., 116., 117., 118.],
        [  0.,   1.,   2., ..., 116., 117., 118.]]),
 [59, 59])

In [162]:
lst = [57, 17, 23, 1, 18, 2]
mean = 118
distribute_to_3pro(lst, mean)

(array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
           1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
           1.,   1.,   1.,   1.,   1

In [32]:
lst = [17, 23, 1, 18, 59]
mean = 118
distribute_to_3(lst, mean)

array([[  0.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,  17.,  18.,  19.,  19.,  19.,
         19.,  23.,  24.,  24.,  24.,  24.,  24.,  24.,  24.,  24.,  24.,
         24.,  24.,  35.,  36.,  36.,  36.,  36.,  40.,  41.,  42.,  42.,
         42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,
         42.,  42.,  42.,  58.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,
         59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,
         59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,
         59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,
         59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,
         59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.,  59.],
       [  0.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,  17.,  18.,  19.,  19.,  19.,
         19.,  23.,  24.,  24.,  24.,  24.,  24.,

In [53]:
a = [1, 5, 2, 3, 4]

In [54]:
b = a[:]

In [58]:
a.remove(2)

In [59]:
a

[1, 3, 4]

In [57]:
b

[1, 5, 2, 3, 4]