In [13]:
def evalt(a, b, op):
    if op == '+':
        return a + b
    elif op == '-':
        return a - b
    elif op == '*':
        return a * b
    else:
        assert False

In [58]:
import numpy as np
def get_maximum_value(dataset):
    nums = dataset[::2]
    nums = [float(num) for num in nums]
    oper = dataset[1::2]
    
    m = len(nums)

    dpm = np.zeros((m+1, m+1))
    dpM = np.zeros((m+1, m+1))
    min_lst = []
    max_lst = []
    for i in range(1, m+1):
        dpm[i][i] = nums[i-1]
        dpM[i][i] = nums[i-1]
    
    for s in range(1, m+1):
        for i in range(1, m-s+1):
            j = i + s
            mini = float('inf')
            maxi = float('-inf')
            for k in range(i, j):
                a = evalt(dpm[i][k], dpm[k+1][j], oper[k-1])
                b = evalt(dpM[i][k], dpM[k+1][j], oper[k-1])
                c = evalt(dpm[i][k], dpM[k+1][j], oper[k-1])
                d = evalt(dpM[i][k], dpm[k+1][j], oper[k-1])
                
                mini = min(mini, a, b, c, d)
                maxi = max(maxi, a, b, c, d)
                
            dpm[i][j] = mini
            dpM[i][j] = maxi
            
    return dpm, dpM

In [59]:
dataset = '5-8+7*4-8+9'
dpm, dpM = get_maximum_value(dataset)

In [60]:
dpm

array([[   0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [   0.,    5.,   -3.,  -10.,  -55.,  -63.,  -94.],
       [   0.,    0.,    8.,   15.,   36.,  -60., -195.],
       [   0.,    0.,    0.,    7.,   28.,  -28.,  -91.],
       [   0.,    0.,    0.,    0.,    4.,   -4.,  -13.],
       [   0.,    0.,    0.,    0.,    0.,    8.,   17.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    9.]])

In [63]:
dpM

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   5.,  -3.,   4.,  25.,  65., 200.],
       [  0.,   0.,   8.,  15.,  60.,  52.,  75.],
       [  0.,   0.,   0.,   7.,  28.,  20.,  35.],
       [  0.,   0.,   0.,   0.,   4.,  -4.,   5.],
       [  0.,   0.,   0.,   0.,   0.,   8.,  17.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   9.]])

In [47]:
dataset = '5+1'
dpm, dpM = get_maximum_value(dataset)

In [48]:
dpM

array([[0., 0., 0.],
       [0., 5., 6.],
       [0., 0., 1.]])

In [49]:
dataset = '5-8+7*4-8+9'
dataset[1::2]

'-+*-+'